version: "3.8"
services:
  unCover:
    image: lucasliebe/uncover-training
    ports:
      - "8501:8501"
    networks:
      - uncover-internal
    depends_on:
      - term-distance
    stdin_open: true
    tty: true

  term-distance:
    image: lucasliebe/uncover-termdistance
    ports:
      - "8000:8000"
    networks:
      - uncover-internal

networks:
  uncover-internal: