version: "3.8"
services:
  unCover:
    image: lucasliebe/uncover-training
    ports:
      - "8501:8501"
    networks:
      - internal
    depends_on:
      - term-distance
    stdin_open: true
    tty: true
  term-distance:
    image: lucasliebe/uncover-termdistance
    expose:
      - 8000
    networks:
      - internal

networks:
  internal:
    driver: bridge