name: unCover
channels:
  - defaults
dependencies:
  - python=3.10.9
  - numpy=1.23.5
  - pandas=1.5.2
  - graphviz=2.50.0
  - pip
  - regex
  - requests
  - openjdk
  - pip:
    - altair==4.2.2
    - beautifulsoup4==4.11.2
    - dominate==2.7.0
    - graphviz==0.20.1
    - keras==2.11.0
    - markdown==3.4.1
    - nltk==3.6.7
    - numpy==1.23.5
    - openai==0.26.5
    - pandas==1.5.2
    - pillow==9.4.0
    - protobuf==3.19.6
    - pyyaml==6.0
    - python-dotenv==0.21.1
    - scikit_learn==1.2.2
    - selenium==4.1.3
    - stanza==1.4.2
    - streamlit==1.19.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-gpu==2.11.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - transformers==4.27.4
