name: unBlock
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=38.0.4
  - h5py=3.7.0
  - hdf5=1.10.6
  - idna=3.4
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.2
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - pytz=2022.7
  - readline=8.2
  - regex=2021.8.3
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - tqdm=4.31.1
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - astunparse==1.6.3
    - async-generator==1.10
    - async-timeout==4.0.2
    - attrs==22.2.0
    - beautifulsoup4==4.11.2
    - bs4==0.0.1
    - cachetools==5.3.0
    - dominate==2.7.0
    - exceptiongroup==1.1.0
    - flatbuffers==23.1.21
    - frozenlist==1.3.3
    - gast==0.4.0
    - google-auth==2.16.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - graphviz==0.20.1
    - grpcio==1.51.1
    - h11==0.14.0
    - importlib-metadata==6.0.0
    - joblib==1.2.0
    - keras==2.11.0
    - libclang==15.0.6.1
    - markdown==3.4.1
    - markupsafe==2.1.2
    - multidict==6.0.4
    - nltk==3.6.7
    - oauthlib==3.2.2
    - openai==0.26.5
    - opt-einsum==3.3.0
    - outcome==1.2.0
    - pillow==9.4.0
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-dotenv==0.21.1
    - pyyaml==6.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit_learn==1.2.2
    - selenium==4.1.3
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4
    - stanza==1.4.2
    - streamlit==1.19.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.11.0
    - tensorflow-gpu==2.11.0
    - tensorflow-io-gcs-filesystem==0.30.0
    - termcolor==2.2.0
    - trio==0.22.0
    - trio-websocket==0.9.2
    - typing-extensions==4.5.0
    - urllib3-secure-extra==0.1.0
    - werkzeug==2.2.3
    - wrapt==1.14.1
    - wsproto==1.2.0
    - yarl==1.8.2
    - zipp==3.14.0
