#!/bin/sh
# read 2 arguments as floats

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <float> <float>" > /app/unCover/logs/errorfile.txt
    exit 1
fi

cd tem/term-distance && conda run -n unCover ./run.sh & sleep 1
sleep 10 # wait until server is up
conda run --no-capture-output -n unCover python3 train_tem_metrics.py --optimize_tem --preprocessed --tem_params "$1,$2"
