#!/bin/sh
# read 2 arguments as floats

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <float> <float>" > /app/unCover/logs/errorfile.txt
    exit 1
fi

cd tem/term-distance && ./run.sh & sleep 1
sleep 10 # wait until server is up
python3 train_tem_metrics.py --tem_params "$1,$2"
